# Generated by Django 3.2.9 on 2021-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='totalScoreFifa',
            field=models.IntegerField(default=0, verbose_name='totaalScore Fifa'),
        ),
        migrations.AddField(
            model_name='customer',
            name='totalScoreMarioKart',
            field=models.IntegerField(default=0, verbose_name='totaalScore Mario Kart'),
        ),
        migrations.AddField(
            model_name='customer',
            name='totalScoreRocketLeague',
            field=models.IntegerField(default=0, verbose_name='totaalScore Rocket League'),
        ),
    ]
