# Generated by Django 3.2.9 on 2021-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20211123_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='totalScoreVersus',
            field=models.IntegerField(default=0, editable=False, verbose_name='totaalScore Versus'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='totalScore',
            field=models.IntegerField(default=0, editable=False, verbose_name='Totaalscore'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='totalScoreFifa',
            field=models.IntegerField(default=0, editable=False, verbose_name='totaalScore Fifa'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='totalScoreMarioKart',
            field=models.IntegerField(default=0, editable=False, verbose_name='totaalScore Mario Kart'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='totalScoreRocketLeague',
            field=models.IntegerField(default=0, editable=False, verbose_name='totaalScore Rocket League'),
        ),
    ]
