# Generated by Django 3.2.9 on 2021-11-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Reclame',
        ),
    ]
