# Generated by Django 3.2.9 on 2021-11-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_rename_image_reclame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reclame',
        ),
    ]
