# Generated by Django 3.2.9 on 2021-11-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_auto_20211126_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matche',
            options={'verbose_name': '1v1 Wedstrijd', 'verbose_name_plural': '1v1 Wedstrijden'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Team Wedstrijden', 'verbose_name_plural': 'Team Wedstrijden'},
        ),
        migrations.AddField(
            model_name='teams',
            name='score',
            field=models.IntegerField(default=0, max_length=30, verbose_name='Behaalde score'),
        ),
    ]
