# Generated by Django 3.2.9 on 2021-11-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_auto_20211126_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Behaalde score'),
        ),
    ]
