# Generated by Django 3.2.9 on 2021-11-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0009_alter_teams_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Teams', 'verbose_name_plural': 'Teams'},
        ),
        migrations.RemoveField(
            model_name='teams',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='score',
        ),
        migrations.AddField(
            model_name='teams',
            name='teamName',
            field=models.CharField(default='', max_length=30, verbose_name='Team naam'),
        ),
        migrations.AddField(
            model_name='teams',
            name='totalScoreVersus',
            field=models.IntegerField(default=0, editable=False, verbose_name='totaalScore Versus'),
        ),
    ]
