# Generated by Django 3.2.9 on 2021-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0010_auto_20211126_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='totalTeamScoreVersus',
            field=models.IntegerField(default=0, verbose_name='totaalScore Versus'),
        ),
    ]
