# Generated by Django 3.2.9 on 2021-11-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0011_teams_totalteamscoreversus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamWedstrijden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(choices=[('Fifa', 'Fifa'), ('Mario_Kart', 'Mario Kart'), ('Rocket_League', 'Rocket League'), ('Versus', 'Versus')], max_length=30, verbose_name='Naam van de game')),
                ('score', models.IntegerField(default=0, verbose_name='Totale score')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='leaderboard.teams', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team Wedstrijden',
                'verbose_name_plural': 'Team Wedstrijden',
            },
        ),
    ]
