# Generated by Django 3.2.9 on 2021-11-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0013_auto_20211126_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='totalTeamScoreArrowSong',
            field=models.IntegerField(default=0, editable=False, verbose_name='totaalScore Arrow Song'),
        ),
        migrations.AddField(
            model_name='teams',
            name='totalTeamScoreCyberShock',
            field=models.IntegerField(default=0, editable=False, verbose_name='totaalScore Cyber Shock'),
        ),
        migrations.AddField(
            model_name='teams',
            name='totalTeamScoreDeadAhead',
            field=models.IntegerField(default=0, editable=False, verbose_name='totaalScore Dead Ahead'),
        ),
        migrations.AddField(
            model_name='teams',
            name='totalTeamScoreQuantumArena',
            field=models.IntegerField(default=0, editable=False, verbose_name='totaalScore Quantum Arena'),
        ),
        migrations.AlterField(
            model_name='teamwedstrijden',
            name='game_id',
            field=models.CharField(choices=[('Versus', 'Versus'), ('Qub3z_Shooter', 'Qub3z Shooter'), ('Dead_Ahead', 'Dead Ahead'), ('Cyber_Shock', 'Cyber Shock'), ('Arrow_Song', 'Arrow Song'), ('Quantum_Arena', 'Quantum Arena')], max_length=30, verbose_name='Naam van de game'),
        ),
    ]
